### ISSUE TITLE
RTL extractor stopped working

### ISSUE THREAD

**Issue by MatrixView** [Reino17/BatchGemist#3]
RTL-XL changed stuff: 

BatchGemist:

```
Voer programma-url in (of 'h' voor hulp):
https://www.rtl.nl/video/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377/

Video nog niet, of niet meer beschikbaar
```

YT-DL:

```
youtube-dl https://www.rtl.nl/video/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377/
[rtl.nl] 206a0db0-9bc8-3a32-bda3-e9b3a9d4d377: Downloading JSON metadata
[rtl.nl] 206a0db0-9bc8-3a32-bda3-e9b3a9d4d377: Downloading m3u8 information
ERROR: unable to download video data: HTTP Error 403: Forbidden

```
It's the same with last weeks videos.

Thanx in advance!
--MatrixView

**Comment by Invictaz** [comment]
Oude urls van RTL:

https://www.rtl.nl/video/2da045e9-7be8-491e-a38a-518336097ed6/uitstel-van-executie/afl-2/

nieuwe URLS:

https://www.rtl.nl/video/5b013a0d-a53d-45d4-a611-fa17136e1703/

Dingen lijken tegenwoordig bij Akamai gehost:

https://rtl-hls-aes-relative.akamaized.net/rtlxl/v166/network/pc/adaptive/components/programma/koffietijd/398975/2018w05/9a550d70-7b06-3b80-b462-8976c190e6d0.ssm/9a550d70-7b06-3b80-b462-8976c190e6d0-audio=125437-video=4030000.m3u8

Dit was zoiets als

http://manifest.us.rtl.nl/10/v166/aes/adaptive/components/actueel/rtlnieuws/376457/2017w46/d4e31e66-e403-33d5-8f44-a3886e42be51.ssm/d4e31e66-e403-33d5-8f44-a3886e42be51.ism/d4e31e66-e403-33d5-8f44-a3886e42be51-audio=125437-video=2221000.m3u8

Ik heb nog wat met Xidel proberen te extraxten maar dat gaat nog niet zo best. @Reino17 weet beter hoe dat moet.

**Comment by Invictaz** [comment]
Gek genoeg doet deze url het nog wel
https://manifest.us.rtl.nl/10/v166/aes/adaptive/components/huistuinkeuken/uitstelvanexecutie/340961/2da045e9-7be8-491e-a38a-518336097ed6.ssm/2da045e9-7be8-491e-a38a-518336097ed6.ism/2da045e9-7be8-491e-a38a-518336097ed6-audio_eng=128000-video=4248000.m3u8

Maar hij maakt ook verbinding naar 
licenseservice.rtl.nl:443 bij afspelen

**Comment by Reino17** [comment]
```
xidel-0.9.7.5706-openssl.exe -s "http://www.rtl.nl/system/s4m/vfd/version=2/uuid=206a0db0-9bc8-3a32-bda3-e9b3a9d4d377/fmt=adaptive/"
-e "let $a:=$json[
          not(
            meta/nr_of_videos_total=0
          )
        ]/concat(
          meta/videohost,
          material/videopath
        ),
        $b:=(
          'a2t',
          'a3t',
          'nettv'
        )
    return (
      $b ! replace(
        $a,
        '.+(/comp.+)m3u8',
        concat(
          'http://pg.us.rtl.nl/rtlxl/network/',
          .,
          '/progressive$1mp4'
        )
      )
    )"
http://pg.us.rtl.nl/rtlxl/network/a2t/progressive/components/videorecorder/30/301978/402905/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377.ssm/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377.mp4
http://pg.us.rtl.nl/rtlxl/network/a3t/progressive/components/videorecorder/30/301978/402905/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377.ssm/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377.mp4
http://pg.us.rtl.nl/rtlxl/network/nettv/progressive/components/videorecorder/30/301978/402905/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377.ssm/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377.mp4
```
Als je deze urls nu probeert te benaderen krijg je:

> ### 403 - Forbidden: Access is denied.
> You do not have permission to view this directory or page using the credentials that you supplied.

Ik ben echter de volgende url tegengekomen...
```
xidel-0.9.7.5706-openssl.exe -s --color=never "https://api.rtlxl.nl/api/2/token" -e "."
{
  "accessToken": "eyJhbGci[...]APKnxS6A",
  "expiresIn": 3600,
  "expiresOn": 1517352659,
  "tokenType": "Bearer",
  "signerCertificate": "MIIF2TCC[...]XmMYEQ==",
  "resource": "https://licenseproxy.rtl.nl"
}
```
...en dat token zou er op de een of andere manier wel eens voor gebruikt kunnen worden. Maar totdat iemand de rtlXL app (waar de progressieve videostreams volgens mij nog steeds gebruikt worden) ontleedt, net zoals Youtube-dl dat heeft gedaan om achter deze urls te komen, blijft dat onduidelijk en is het wat mij betreft voor nu einde oefening voor de progressieve videostreams.

De hls videostreams, zoals op dit moment ontleed, doen het nog steeds gewoon...
```
xidel-0.9.7.5706-openssl.exe -s --color=never "http://www.rtl.nl/system/s4m/vfd/version=2/uuid=206a0db0-9bc8-3a32-bda3-e9b3a9d4d377/fmt=adaptive/"
-f "$json[
      not(
        meta/nr_of_videos_total=0
      )
    ]/concat(
      meta/videohost,
      material/videopath
    )"
-e "extract(
      tokenize(
        $raw,
        '#EXT-X-STREAM-INF:'
      )[
        contains(
          .,
          '1280x720'
        )
      ],
      '(.+m3u8)',
      1
    ) ! system(
      x'cmd /c "FFMpeg\ffmpeg-N-87867-g0655810-win32-static_legacy.exe" -i {.} 2>&1'
    )"
ffmpeg version N-87867-g0655810-Reino Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.2.0 (GCC)
[...]
[hls,applehttp @ 04cadd60] Opening 'https://licenseservice.rtl.nl/aes/GetKey/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377' for reading
[hls,applehttp @ 04cadd60] Opening 'crypto+http://rtl-hls-aes.akamaized.net/10/v166/aes/adaptive/components/videorecorder/30/301978/402905/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377.ssm/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377.ism/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377-audio=125437-video=4072000-1.ts' for reading
[...]
Input #0, hls,applehttp, from 'http://manifest.us.rtl.nl/10/v166/aes/adaptive/components/videorecorder/30/301978/402905/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377.ssm/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377.ism/206a0db0-9bc8-3a32-bda3-e9b3a9d4d377-audio=125437-video=4072000.m3u8':
  Duration: 00:58:25.00, start: 10.000000, bitrate: 0 kb/s
  Program 0
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
    Metadata:
      variant_bitrate : 0
```
...maar voor hoe lang nog? Op hun website gebruiken ze al een andere api zo lijkt het.
Ik had vanavond niet veel tijd. Ik zal er morgen naar kijken.

**Comment by Invictaz** [comment]
@Reino17 Ik heb je hierover gemaild.

**Comment by MatrixView** [comment]
@Reino17 Works well with HLS streams, thanx a lot!
