### ISSUE TITLE
Algemene of per broadcaster zoekfunctie

### ISSUE THREAD

**Issue by Invictaz** [Reino17/BatchGemist#5]
NPO-programma zoekt in de npo programma's. 
Het zou mooi zijn als je zoiets had als 

kijk-programma
rtlxl-programma
dumpert-programma

of een algemene zoekfunctie die alleen de eerste 20 resultaten weergeeft

**Comment by Reino17** [comment]
Functionaliteit voor rtlXL en Kijk toegevoegd in respectievelijk ee83286 en 083bf32.
